name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macOS-latest
    steps:
      - name: Install Infer Brew Package
        run: brew install infer
      - name: Code Scan 
        run: infer run -- clang -c ObjectiveC\ CodeQL\ Test/ViewController.m
